### ISSUE TITLE
Looks like this isn't compatible with rspec 3.0

### ISSUE THREAD

**Issue by axlekb** [should-not/should_not#1]

**Comment by MGotink** [comment]
You can fix this for now by defining

``` rb
config.expose_current_running_example_as :example
```

in the config block in spec_helper.rb.

I've created a PR which fixes RSpec 3 support: https://github.com/should-not/should_not/pull/2

**Comment by mark-rushakoff** [comment]
Should be fixed in version 1.1.0 of the gem. Please reopen if that is not the case.
